---
- name: Check if Flannel is running
  ansible.builtin.shell: "kubectl get ds --all-namespaces | grep flannel"
  register: flannel_ds
  ignore_errors: true
  changed_when: false

- name: Deploy Flannel
  ansible.builtin.shell: "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
  when: flannel_ds is failed
  changed_when: false
