---
- name: Install requirements packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: true

- name: Add docker repo
  block:
    - name: Docker | Get armored GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg.armor
        checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
        mode: "0644"
    - name: Docker | De-armor GPG key
      ansible.builtin.shell: gpg --dearmor < /etc/apt/keyrings/docker.gpg.armor > /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
    - name: Docker | Update GPG key permission
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: "0644"
    - name: Docker | apt source
      ansible.builtin.apt_repository:
        repo:
          "deb [arch={{ arch_map[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true
      vars:
        arch_map:
          x86_64: amd64
          aarch64: arm64

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    update_cache: true

- name: Ensure containerd is running and enabled
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: started

- name: Set default config for containerd
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    mode: "0644"
  notify: Restart containerd
